#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

APP_DIR="/home/eli/app/momentum-ops"
COMPOSE_FILE="${APP_DIR}/infrastructure/deploy/docker-compose.prefect.yml"
# Suggestion: Use a staging-specific .env if available to isolate DB/API keys
ENV_FILE="/mnt/Main/Apps/momentum-ops/ephemeral/.env"
PREFIX="feature/ingestion/"
REMOTE="origin"

echo "--- Staging Deployment Started ---"

# 1. Fetch all remote updates
echo "Fetching from $REMOTE..."
git -C "${APP_DIR}" fetch $REMOTE --prune

# 2. Identify the latest branch with the prefix
LATEST_BRANCH=$(git -C "${APP_DIR}" branch -r --sort=-committerdate | grep "$REMOTE/$PREFIX" | head -n 1 | sed "s/.*$REMOTE\///" | xargs)

if [ -z "$LATEST_BRANCH" ]; then
    echo "Error: No branches found matching prefix $PREFIX"
    exit 1
fi

echo "Targeting latest branch: $LATEST_BRANCH"

# 3. Force checkout and pull the latest code
git -C "${APP_DIR}" checkout -B "$LATEST_BRANCH" "$REMOTE/$LATEST_BRANCH"
git -C "${APP_DIR}" pull $REMOTE "$LATEST_BRANCH"

# 4. Apply Docker configuration
# Note: Added '-p momentum-ops-stg' to ensure container names don't collide if you ever move them to the same host
echo "Applying Docker configuration for Staging..."
docker compose -p momentum-ops-stg -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" up -d --build

# 5. Sync Prefect deployments
# Ensure the container name matches the one generated by the -p flag (usually momentum-ops-stg-worker-1)
# Or use the generic 'momentum-worker' if your compose file explicitly names the container.
WORKER_CONTAINER=$(docker ps --filter "name=worker" --format "{{.Names}}" | head -n 1)

echo "Syncing Prefect deployments from prefect.yaml using container: $WORKER_CONTAINER"
docker exec "$WORKER_CONTAINER" prefect deploy --all

echo "--- Staging Deployment Complete ---"
docker logs --tail 20 "$WORKER_CONTAINER"